<?php

// Presentation settings only: permissions and data are not changed.
return [
    'calendar' => ['label' => 'Calendar', 'group' => 'Overview'],
    'employees' => ['label' => 'Employees', 'group' => 'Workforce Management'],
    'organization-chart' => ['label' => 'Organization Chart', 'group' => 'Workforce Management'],
    'branches' => ['label' => 'Branches', 'group' => 'Organization Structure'],
    'departments' => ['label' => 'Departments', 'group' => 'Organization Structure'],
    'designations' => ['label' => 'Designations', 'group' => 'Organization Structure'],
    'holidays' => ['label' => 'Holidays', 'group' => 'Organization Structure'],
    'announcements' => ['label' => 'Announcements', 'group' => 'Organization Structure'],
    'award-types' => ['label' => 'Award Types', 'group' => 'Organization Structure'],
    'document-types' => ['label' => 'Document Types', 'group' => 'Organization Structure'],
    'attendance-records' => ['label' => 'Attendance Records', 'group' => 'Attendance'],
    'time-entries' => ['label' => 'Timesheet', 'group' => 'Attendance'],
    'biometric-attendance' => ['label' => 'Biometric Attendance', 'group' => 'Attendance'],
    'attendance-regularizations' => ['label' => 'Attendance Regularizations', 'group' => 'Attendance'],
    'shifts' => ['label' => 'Shifts', 'group' => 'Attendance'],
    'attendance-policies' => ['label' => 'Attendance Policies', 'group' => 'Attendance'],
    'leave-applications' => ['label' => 'Leave Applications', 'group' => 'Leave Management'],
    'leave-balances' => ['label' => 'Leave Balances', 'group' => 'Leave Management'],
    'leave-types' => ['label' => 'Leave Types', 'group' => 'Leave Management'],
    'leave-policies' => ['label' => 'Leave Policies', 'group' => 'Leave Management'],
    'job-postings' => ['label' => 'Job Postings', 'group' => 'Recruitment'],
    'candidates' => ['label' => 'Candidates', 'group' => 'Recruitment'],
    'interviews' => ['label' => 'Interviews', 'group' => 'Recruitment'],
    'offers' => ['label' => 'Offers', 'group' => 'Recruitment'],
    'candidate-onboarding' => ['label' => 'Candidate Onboarding', 'group' => 'Recruitment'],
    'candidate-assessments' => ['label' => 'Candidate Assessments', 'group' => 'Recruitment'],
    'onboarding-checklists' => ['label' => 'Onboarding Checklists', 'group' => 'Recruitment'],
    'checklist-items' => ['label' => 'Checklist Items', 'group' => 'Recruitment'],
    'career-page' => ['label' => 'Career', 'group' => 'Recruitment'],
    'job-categories' => ['label' => 'Job Categories', 'group' => 'Recruitment'],
    'job-types' => ['label' => 'Job Types', 'group' => 'Recruitment'],
    'job-locations' => ['label' => 'Job Locations', 'group' => 'Recruitment'],
    'candidate-sources' => ['label' => 'Candidate Sources', 'group' => 'Recruitment'],
    'interview-types' => ['label' => 'Interview Types', 'group' => 'Recruitment'],
    'interview-rounds' => ['label' => 'Interview Rounds', 'group' => 'Recruitment'],
    'offer-templates' => ['label' => 'Offer Templates', 'group' => 'Recruitment'],
    'custom-questions' => ['label' => 'Custom Questions', 'group' => 'Recruitment'],
    'awards' => ['label' => 'Awards', 'group' => 'Employee Lifecycle'],
    'promotions' => ['label' => 'Promotions', 'group' => 'Employee Lifecycle'],
    'employee-transfers' => ['label' => 'Transfers', 'group' => 'Employee Lifecycle'],
    'warnings' => ['label' => 'Warnings', 'group' => 'Employee Lifecycle'],
    'resignations' => ['label' => 'Resignations', 'group' => 'Employee Lifecycle'],
    'terminations' => ['label' => 'Terminations', 'group' => 'Employee Lifecycle'],
    'trips' => ['label' => 'Trips', 'group' => 'Employee Lifecycle'],
    'complaints' => ['label' => 'Complaints', 'group' => 'Employee Lifecycle'],
    'employee-reviews' => ['label' => 'Employee Reviews', 'group' => 'Performance Management'],
    'employee-goals' => ['label' => 'Employee Goals', 'group' => 'Performance Management'],
    'review-cycles' => ['label' => 'Review Cycles', 'group' => 'Performance Management'],
    'performance-indicators' => ['label' => 'Indicators', 'group' => 'Performance Management'],
    'goal-types' => ['label' => 'Goal Types', 'group' => 'Performance Management'],
    'performance-indicator-categories' => ['label' => 'Indicator Categories', 'group' => 'Performance Management'],
    'employee-trainings' => ['label' => 'Employee Trainings', 'group' => 'Training & Development'],
    'training-sessions' => ['label' => 'Training Sessions', 'group' => 'Training & Development'],
    'training-programs' => ['label' => 'Training Programs', 'group' => 'Training & Development'],
    'training-assessments' => ['label' => 'Training Assessments', 'group' => 'Training & Development'],
    'training-types' => ['label' => 'Training Types', 'group' => 'Training & Development'],
    'payslips' => ['label' => 'Payslips', 'group' => 'Payroll Management'],
    'payroll-runs' => ['label' => 'Payroll Runs', 'group' => 'Payroll Management'],
    'employee-salaries' => ['label' => 'Employee Salaries', 'group' => 'Payroll Management'],
    'salary-components' => ['label' => 'Salary Components', 'group' => 'Payroll Management'],
    'assets' => ['label' => 'Assets', 'group' => 'Asset Management'],
    'asset-types' => ['label' => 'Asset Types', 'group' => 'Asset Management'],
    'meetings' => ['label' => 'Meetings', 'group' => 'Meetings'],
    'action-items' => ['label' => 'Action Items', 'group' => 'Meetings'],
    'meeting-types' => ['label' => 'Meeting Types', 'group' => 'Meetings'],
    'meeting-rooms' => ['label' => 'Meeting Rooms', 'group' => 'Meetings'],
    'hr-documents' => ['label' => 'HR Documents', 'group' => 'Documents & Contracts'],
    'employee-contracts' => ['label' => 'Employee Contracts', 'group' => 'Documents & Contracts'],
    'document-acknowledgments' => ['label' => 'Acknowledgments', 'group' => 'Documents & Contracts'],
    'contract-templates' => ['label' => 'Contract Templates', 'group' => 'Documents & Contracts'],
    'document-templates' => ['label' => 'Document Templates', 'group' => 'Documents & Contracts'],
    'contract-types' => ['label' => 'Contract Types', 'group' => 'Documents & Contracts'],
    'document-categories' => ['label' => 'Document Categories', 'group' => 'Documents & Contracts'],
    'media' => ['label' => 'Media Library', 'group' => 'Communications & Content'],
    'users' => ['label' => 'Users', 'group' => 'System Users'],
    'roles' => ['label' => 'Roles', 'group' => 'System Users'],
    'plans' => ['label' => 'Plans', 'group' => 'Plans'],
    'plan-requests' => ['label' => 'Plan Requests', 'group' => 'Plans'],
    'plan-orders' => ['label' => 'Plan Orders', 'group' => 'Plans'],
    'referral' => ['label' => 'Referral Program', 'group' => 'System Control'],
    'landing-page' => ['label' => 'Landing Page', 'group' => 'System Control'],
    'contacts' => ['label' => 'Contact Inquiries', 'group' => 'System Control'],
    'newsletters' => ['label' => 'Newsletter', 'group' => 'System Control'],
    'currencies' => ['label' => 'Currency', 'group' => 'System Control'],
    'birthdays' => ['label' => 'Today\'s Birthdays', 'group' => 'Dashboard'],
];
