<?php

namespace App\Support;

use App\Models\Employee;
use App\Models\Setting;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class EmployeeFields
{
    public const KEY = 'employee_fields';

    public static function values(): array
    {
        $owner = ModuleVisibility::ownerId();
        $saved = $owner ? json_decode(Setting::where('user_id', $owner)->where('key', self::KEY)->value('value') ?? '{}', true) : [];
        $values = [];
        foreach (config('employee-fields') as $key => $field) {
            $value = is_array($saved) ? ($saved[$key] ?? []) : [];
            $default = is_array($value) ? ($value['default'] ?? $field['default'] ?? null) : ($field['default'] ?? null);
            if (($field['type'] ?? 'none') === 'none' || ($field['locked'] ?? false)) {
                $default = null;
            } elseif (Validator::make(['value' => $default], ['value' => $field['rules']])->fails()) {
                $default = $field['default'];
            }
            $values[$key] = [
                'visible' => ($field['locked'] ?? false) || !is_array($value) || ($value['visible'] ?? true) !== false,
                'default' => $default,
            ];
        }
        // Also protect against an inconsistent legacy/imported configuration.
        if (!$values['branch_id']['visible']) $values['department_id']['visible'] = false;
        if (!$values['department_id']['visible']) $values['designation_id']['visible'] = false;
        return $values;
    }

    public static function visibility(): array
    {
        // Defaults can contain HR data: only the settings page receives their values.
        return array_map(fn ($field) => $field['visible'], self::values());
    }

    public static function prepare(Request $request, ?Employee $employee = null): array
    {
        // Start with a fresh file cache in case earlier middleware inspected uploads.
        $request = Request::createFrom($request);
        $values = self::values();
        foreach ($values as $key => $value) {
            if ($value['visible']) continue;
            if ($key === 'employee_id') continue; // Always generated by the existing controller.
            $request->files->remove($key);
            if ($key === 'profile_image' || $key === 'documents') {
                $request->merge([$key => $key === 'documents' ? [] : null]);
                continue;
            }
            $column = config("employee-fields.$key.column", $key);
            $request->merge([$key => $employee ? $employee->getRawOriginal($column) : $value['default']]);
        }
        return [$request, $values];
    }

    public static function rules(array $rules, array $values, bool $editing = false): array
    {
        foreach ($values as $key => $value) {
            if ($value['visible']) continue;
            foreach (array_keys($rules) as $ruleKey) {
                if ($ruleKey !== $key && !str_starts_with($ruleKey, $key.'.')) continue;
                // The database values of hidden fields must survive unrelated edits unchanged.
                if ($editing || $key === 'documents' || $key === 'profile_image') {
                    unset($rules[$ruleKey]);
                } else {
                    $rules[$ruleKey] = config("employee-fields.$key.rules", 'nullable');
                }
            }
            if (!$editing && !in_array($key, ['documents', 'profile_image', 'employee_id'])) {
                $rules[$key] = config("employee-fields.$key.rules", 'nullable');
            }
        }
        return $rules;
    }
}
